channels:
  - conda-forge
  - conda
dependencies:
  - python>=3.10
  - matplotlib
  - pandas
  - numpy
  - hydra-core
  - flake8
  - pytest
  - coverage
  - ipykernel  # for running jupyter in vscode
  - conda-build
