name: Makefile CI

on:

  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: make environment

    - name: Check linting
      run: make lint

    - name: Run tests
      run: make test
